### ISSUE TITLE
Allow tag and audio_event filters to include ids of other table in projection.

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-server#181]
The idea here is to enable tags and audio_events to be associated with each other on the client side. Currently, it is possible to compose a reduced set of queries to get the tags for a number of audio_events. However, there is no clear way to associate the tags and audio_events.

The proposal is to enable a special projection of `taggings` that includes the information from the `audio_events_tags` table.

**Comment by atruskie** [comment]
Additional refinements:

 - projection can only work on the top level field (i.e. on `taggings` for inclusion or exclusion as a whole)
 - filtering on `taggings`'s fields is not not necessary (but may be supported already)
 - ordering by `taggings` is not necessary
 - general rule with many-to-many is that including association ids in resource is OK (as an exception to normal rules of only allowing whole resources)
   - in this case, including the whole `taggings` object is considered OK because the only important information in that relation is the `tag_id` and then some random dates... might as well send 'em back
