### ISSUE TITLE
Ensure it is possible to query/filter resque jobs based on some kind of field

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-server#192]
Related to #191 and #193

For our chosen architecture, where we do not track sub-jobs, we need to be able to query resque to find resque jobs that have a custom_job's (i.e. the parent) id.

Whether this id is stored in the payload or in some other way remains unclear.

Implement such a filtering function

**Comment by cofiem** [comment]
This issue is mainly about being able to report the number of resque queued, working, successful, and failed jobs for a particular `analysis_job`. One resque job processes a single `audio_recording`.

The way the counts are updated is complicated and prone to race conditions.
- (push) if workers update the stats, race conditions are very likely to occur. However, each worker just needs to send the analysis_id, and the status to increment. This remains ambiguous - if a failed status is sent, is working or queued decremented? the status per job is not stored.
- (pull) if stats are updated on demand or on a regular schedule by the web server, then the challenges below apply

This is possible in theory:
- queued jobs: filter the appropriate queue to find jobs matching an analysis_job id
- working jobs: get all the working jobs, check the analysis_job id
- failed jobs: check the failed queue for any jobs of the `Analysis` type with a matching analysis_job id
- successful jobs: total jobs pushed to the queue when the analysis_job was started - (queued jobs + working jobs + failed jobs)

In practice there are some challenges:
- the queued, working, and failed jobs lists have to be iterated, even if an operation that filters is used (e.g. [SCAN](http://redis.io/commands/scan). This could take a long time if there are lots of jobs. This operation could probably not be done regularly, or on demand.
- Since successful jobs are simply removed, there is no 'source of truth`: all values would be approximations.
- the same problems apply to finding a particular job. It is not possible to store information about individual jobs.

The other option is to have a job item table to store very basic information. This has the benefit of removing all the challenges of using redis only. However, it is duplicate information, and needs to be kept in sync with the resque jobs. This would probably be done through workers pushing information to the web server.

**Comment by atruskie** [comment]
The way i see it there are three options (I'm rehashing some of what you said, just thinking, no decisions):

# options

## (push): 
  - description: workers update stats on `analysis_job` record through HTTP+REST
  - pros
     - simplicity
     - does not need a meta-tracker (see below)
  - cons
    - no tracking of job items
    - race conditions
    - not normal form
    - cannot restart a job item
  - opportunities
    - We could defensively code for race conditions. Something like (SQL pseudo code):

        ```
        START TRANSACTION;
        IF (SELECT modified_date FROM analysis_jobs WHERE id = ?id?) = ?modified_date? THEN
            UPDATE ...
        ELSE
            SELECT * FROM FROM analysis_jobs WHERE id = ?id?
        END;
        COMMIT;
        ```
        Unsuccessful attempts (race conditions avoided in DB because of transactions) because race condition in application layer are returned the updated record. Relevant progress is incremented on new record, attempt to save again, continue until success
 
## (pull):
  - description: statuses are updated by querying the redis instance
  - pros
    - no race conditions
    - workers don't need to know about REST API
  - cons:
    - complex - need to check multiple queues
    - time consuming - needs to be done with scan
    - cannot be done on demand (needs a meta job that every n minutes summarizes stats and updates tracking analysis_job in postgres )
    - indirect, treats redis as a database not a KVP store
    - rails object serialization on thousands of records will consume serious CPU
  - opportunities
    - jobs items need to **not be deleted** immediately.
    - scan implements GLOB pattern matching and we can adjust COUNT (pattern matching with globs, tune SCAN iterator to scan for bigger chunks (1000 records at a time) so 30,000 scans can be turned into 300 (COUNT set as 10 changed to 1000), mostly empty iterator results equals no perf penalty)
    - scan can parse a million records on consumer hardware in 40ms - avoiding it may be a case of premature optmization
      - biggest blocker will be Rails/Ruby serialization IMO

## (push+with tracking table):
  - description: workers push updates via HTTP+REST but we have dedicated `analysis_jobs_items` table for tracking progress
  - pros
    - no race conditions
    - we can restart/retry job items
    - data stored as normal form
    - summarizing progress is just a GROUP BY and COUNT SQL query
    - progress summary _can_ still be kept aggregated in `analysis_jobs` obviating the need to update progress on _every_ request.
    - perfect knowledge situation
    - redis jobs do not need to be persisted, can be deleted as soon as completed (either fail or success)
  - cons:
    - **massive duplication of data - why have redis?**
    - synchronization issues? maybe?
    - workers need to know about the REST API
  - opportunities
    - analysis_job_item records do not need to be permanently kept 
      - when a job finishes, csv export relevant rows, save to job results folder, delete records
      - this depends on keeping the current summary statistics in the `analysis_jobs` table
    - redis payload may be able to be reduced in size (API calls can fetch configs (see below) and other things like scripts).

# other notes

- Job items should not be removed in the pull scenario. We should utilize the [whatever plugin it is] plugin to keep the jobs alive/persisted until the parent analysis_job is finished.

- Memory is important for redis. https://github.com/QutBioacoustics/baw-workers/issues/31 is particulrarly important. If the suggestion from it is taken, we can scratch REST API off pros/cons list since workers will need to know about it to get their config files anyway.

- a potential schema for `analysis_jobs_items`:  

**analysis_jobs_items**(<u>analysis_job_id, audio_recording_id</ul>, status, updated_at)   
OR (more complex)  
 **analysis_jobs_items**(<u>analysis_job_id, audio_recording_id</ul>, status, queued_at, working_at, completed_at)

**Comment by atruskie** [comment]
I've spoken to @proe about this issue.

He's pushing for:
- being able to cancel analysis jobs
- being able to re-run an analysis job item / resque task if it fails
- ensuring we can track progress for individual job items

We purposely avoided these features because they add complexity in the first iteration. However, given the issues discussed in this thread, choosing the _push+with tracking table_ option seems to be the best way forward.

Paul also wondered if we're reinventing the wheel a bit too much. He made a good point that job systems are age old technologies and there's likely a system we don't have to build ourselves. Questions that follow:
 - is there anything suitable? e.g. traditional HPC batch systems. I don't believe we've checked
 - is SideKiq the answer to any of this?
 - even if we found such a system:
   - is the pain of customising it worth it? 
     - at least with a custom system it does exactly what we want.
     - though we don't really have a custom system, we have custom slapped on top of resque
   - sunk cost fallacy: we've invested this much time, is it worth sticking with what we got?

NB: I added `message_queue_id` field to the proposed schema above - this would be the resque job id

**Comment by cofiem** [comment]
We have looked into batch systems before, but that was back in Windows days.

For Linux and/or Ruby:

- [SLURM (Simple Linux Utility for Resource Management)](https://computing.llnl.gov/linux/slurm/sbatch.html)
- [Open Grid Scheduler (SGE / Sun grid Engine)](http://gridscheduler.sourceforge.net/)
- [Oracle Grid Scheduler](http://www.oracle.com/us/products/tools/oracle-grid-engine-075549.html)
- [PBS / Torque](https://en.wikipedia.org/wiki/TORQUE) (the Pro version?? is used by QUT HPC)
- [G NQS](http://gnqs.sourceforge.net/docs/starter_pack/alternatives/index.html) (seems rather old)
- [Platform LSF](http://www-03.ibm.com/systems/platformcomputing/products/lsf/)
- [HTCondor](http://research.cs.wisc.edu/htcondor/)
- [moab](http://www.adaptivecomputing.com/products/hpc-products/moab-lite/)
- [OAR](http://oar.imag.fr/)
- [Sidekiq](http://sidekiq.org/)
- [Resque](https://github.com/resque/resque)
- [openlava](http://www.openlava.org/)

**Comment by atruskie** [comment]
Thanks for the list. Just evaluating if any of these are useful will take time. Large API surfaces, well outside my area of expertise. 

I can build a distributed web system... 

Perhaps this is worth talking to the QUT HPC folks. We can't actually use their systems because they're so sandboxed (and that would also add an infrastructure dependency which wouldn't be appropriate) but they have experience setting up and maintaining these systems.

**Comment by cofiem** [comment]
No worries. It probably is worth talking with QUT HPC, at least just to get their take on what the scheduling systems do, if they support our use cases, and which ones they've tried.
